steps:
  - label: ":pulumi: Preview"
    command: pulumi whoami
    plugins:
      - cnunciato/pulumi:
          use_oidc: true
          audience: "urn:pulumi:org:cnunciato"
          pulumi_token_type: "urn:pulumi:token-type:access_token:personal"
          pulumi_token_scope: "user:cnunciato"
