steps:
  - label: ":pulumi: Preview"
    command: |
      pulumi whoami
      echo $$NX_BASE
      echo $$NX_HEAD
    plugins:
      - pulumi:
          version: 3.184.0
          use_oidc: true
          audience: "urn:pulumi:org:cnunciato"
          pulumi_token_type: "urn:pulumi:token-type:access_token:personal"
          pulumi_token_scope: "user:cnunciato"
      - nx-set-shas:
          api-token: "$${GRAPHQL_API_TOKEN}"
      # - secrets:
      #     variables:
      #       GRAPHQL_API_TOKEN: GRAPHQL_API_TOKEN
