steps:
  - label: ":pulumi: Pulumi"
    command: |
      pulumi whoami
    plugins:
      - pulumi:
          version: 3.184.0
          use_oidc: true
          audience: "urn:pulumi:org:cnunciato"
          pulumi_token_type: "urn:pulumi:token-type:access_token:personal"
          pulumi_token_scope: "user:cnunciato"

  - label: ":nx: Set SHAs (with env)"
    command: |
      echo $$NX_BASE
      echo $$NX_HEAD
    plugins:
      - nx-set-shas
      - secrets:
          variables:
            GRAPHQL_API_TOKEN: GRAPHQL_API_TOKEN

  - label: ":nx: Set SHAs (with param)"
    command: |
      echo $$NX_BASE
      echo $$NX_HEAD
      export MY_TOKEN="$$(buildkite-agent secret get GRAPHQL_API_TOKEN)"
    plugins:
      # - secrets:
      #     variables:
      #       GRAPHQL_API_TOKEN: GRAPHQL_API_TOKEN
      - nx-set-shas:
          api-token: $$MY_TOKEN
